### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#12]
Duración: 4 horas.
Descripción: Realizar el diagrama de clases de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
Diagrama de Clases

![diagrama_de_clases](https://cloud.githubusercontent.com/assets/25873547/25437111/f4490cac-2a5a-11e7-8383-20f169f794c9.PNG)
