### ISSUE TITLE
MER

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#14]
Duración: 4 horas.
Descripción: Realizar el modelo entidad relación de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
Modelo Entidad-Relación de YourCode
![mer](https://cloud.githubusercontent.com/assets/25873547/25834048/ff0ced0e-343a-11e7-80da-b0fbebc73321.PNG)

**Comment by MauricioCaviedes21** [comment]
![mer](https://user-images.githubusercontent.com/25873547/27115083-e6a14a84-508d-11e7-963b-fba19957eec9.PNG)

**Comment by MauricioCaviedes21** [comment]
![captura2](https://user-images.githubusercontent.com/25873547/27140843-2dc4ed90-50ec-11e7-9b15-ed1a3a1784b3.PNG)
