### ISSUE TITLE
DER

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#15]
Duración: 4 horas.
Descripción: Realizar el diagrama entidad relación de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
Diagrama Entidad-Relación
![der](https://cloud.githubusercontent.com/assets/25873547/25880288/2ae0dfdc-34fc-11e7-8a05-ead97929a4df.PNG)

**Comment by MauricioCaviedes21** [comment]
![der](https://user-images.githubusercontent.com/25873547/27115072-d8e4dd02-508d-11e7-8b23-30e854353408.PNG)

**Comment by MauricioCaviedes21** [comment]
![captura2](https://user-images.githubusercontent.com/25873547/27140670-c1cebbca-50eb-11e7-85df-08955fb5e523.PNG)

**Comment by MauricioCaviedes21** [comment]
![captura1](https://user-images.githubusercontent.com/25873547/27140799-14a23d54-50ec-11e7-8a0d-0f8776c5ecfd.PNG)
