### ISSUE TITLE
Diccionario de datos

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#18]
Duración: 8 horas.
Descripción: Realizar el diccionario de datos de la aplicación YourCode usando una plantilla correspondiente.

**Comment by MauricioCaviedes21** [comment]
Diccionario de Datos
[Diccionario de Datos.pdf](https://github.com/YourCodeUnillanos/YourCode2/files/1075194/Diccionario.de.Datos.pdf)

**Comment by MauricioCaviedes21** [comment]
[diccionariodatosmauricio.pdf](https://github.com/YourCodeUnillanos/YourCode2/files/1075301/diccionariodatosmauricio.pdf)
