### ISSUE TITLE
Diagrama de casos de uso

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#3]
Duración: 4 horas.
Descripción: Realizar el diagrama de casos de uso sobre los requisitos funcionales de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
Diagrama de Casos de Uso
![casos_de_usos](https://cloud.githubusercontent.com/assets/25873547/25436877/36f57898-2a5a-11e7-830e-14f308131ba8.PNG)
