### ISSUE TITLE
Ficha de casos de uso

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#4]
Duración: 8 horas.
Descripción: Realizar la ficha de casos de uso respecto al diagrama de casos de uso de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
Fichas de Casos de Uso.

[Fichas de Caso de Uso.pdf](https://github.com/YourCodeUnillanos/YourCode2/files/980971/Fichas.de.Caso.de.Uso.pdf)
