### ISSUE TITLE
Estimación de tiempo, costo y esfuerzo

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#5]
Duración: 8 horas.
Descripción: Realizar la estimación de tiempo, costo y esfuerzo usando una herramienta web. Se debe planificar completamente el costo, tiempo y responsable de cada tarea. Desarrollar un diagrama de Gantt.

**Comment by ingalexis** [comment]
https://yourcodes.aceproject.com
