### ISSUE TITLE
Requerimientos funcionales y no funcionales

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode2#8]
Duración: 2 horas.
Descripción: Definir los requerimientos no funcionales de la aplicación YourCode. Entregar un documento donde se especifiquen los requerimientos funcionales y no funcionales.

**Comment by MauricioCaviedes21** [comment]
Requerimientos Funcionales y No Funcionales
[Descripción general.docx](https://github.com/YourCodeUnillanos/YourCode2/files/958503/Descripcion.general.docx)

**Comment by fabiiancano** [comment]
Reestructurar los requerimientos no funcionales de acuerdo a lo requerido. Guardar los requerimientos en formato PDF.

**Comment by MauricioCaviedes21** [comment]
Reestructuración de los requerimientos funcionales y no funcionales
[Descripción general.pdf](https://github.com/YourCodeUnillanos/YourCode2/files/968843/Descripcion.general.pdf)
